### ISSUE TITLE
Add Readme for fonts description and add new fonts

### ISSUE THREAD

**Issue by akkefa** [urduhack/urdu-fonts#1]
This is the repo contains fonts which support the Urdu language.

**Comment by rayyan17** [comment]
@akkefa I have created a branch for 500 different Urdu fonts.

**Comment by akkefa** [comment]
@rayyan17 Add all fonts in the fonts dir.  So others also use it.

**Comment by rayyan17** [comment]
@akkefa I have updated the code and uploaded the files.
